# -*- coding: utf-8 -*-
"""HW Week 2-3_Marina Irdayanti 1301174319

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12Vy0iIjRu1ubhR-M9OSVxZXI_PBooLyE
"""

#1 Bisecant Method

import numpy as np

def f(h):
  f1 = 0.5*np.pi
  f2 = np.arcsin(h)
  f3 = h *np.sqrt(1-(h**2))
  return 12.4 - 10*(f1-f2-f3)
  
a = 0 
b = 0.5
TOL = 10**-2
N0 = 1000

i = 1
FA = f(a)

while (i <= N0):
  p = a + (b-a)/2
  FP = f(p)
  print("{} {} {} {} {}".format(i,a,b,p,FP))
  
  if (FP==0) or (b-a)/2 < TOL:
    print("Root is {}".format(p))
    break
  
  i= i+1
  if (FA*FP > 0):
    a = p
    FA = FP
  else:
    b = p

#2A Secant Method

import numpy as np

def f(a):
  l = 89
  h = 49
  D = 55
  b1 = np.radians(11.5)
  A = l * np.sin(b1)
  B = l * np.cos(b1)
  C = (h + 0.5*D)*np.sin(b1)-0.5*D*np.tan(b1)
  E = (h + 0.5*D)*np.cos(b1)-0.5*D
  f1 = A*np.sin(a)*np.cos(a)
  f2 = B*(np.sin(a)**2)
  f3 = -C*np.cos(a)
  f4 = -E*np.sin(a)
  return  f1 + f2 + f3 + f4

#def f_a(a):
 # D = 55
 # return f(a, D)

#def f_b(a):
 # D = 30
 # return f(a, D)


p0 =  0
p1 =  1
TOL =  10**-4
N0 =  1000

i = 2
q0 = f(p0)
q1 = f(p1)
print("1 {} {} ".format(i,p0,f(p0)))
while (i <= N0):
  p =  p1-q1*(p1-p0)/(q1-q0)
  FP = f(p)
  print("{} {} {}".format(i,p,FP))
  
  if (abs(p-p1) < TOL) :
    print("Root is {}".format(p))
    break
  
  i=i+1
  p0=p1
  q0=q1
  p1=p
  q1=f(p)

#2B Secant Method

import numpy as np

def f(a):
  l = 89
  h = 49
  D = 30
  b1 = np.radians(11.5)
  A = l * np.sin(b1)
  B = l * np.cos(b1)
  C = (h + 0.5*D)*np.sin(b1)-0.5*D*np.tan(b1)
  E = (h + 0.5*D)*np.cos(b1)-0.5*D
  f1 = A*np.sin(a)*np.cos(a)
  f2 = B*(np.sin(a)**2)
  f3 = -C*np.cos(a)
  f4 = -E*np.sin(a)
  return  f1 + f2 + f3 + f4

p0 =  0
p1 =  1
TOL =  10**-4
N0 =  1000

i = 2
q0 = f(p0)
q1 = f(p1)
print("1 {} {} ".format(i,p0,f(p0)))
while (i <= N0):
  p =  p1-q1*(p1-p0)/(q1-q0)
  FP = f(p)
  print("{} {} {}".format(i,p,FP))
  
  if (abs(p-p1) < TOL) :
    print("Root is {}".format(p))
    break
  
  i=i+1
  p0=p1
  q0=q1
  p1=p
  q1=f(p)

